# Generated by Django 6.0.4 on 2026-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="inventory_reserved",
            field=models.BooleanField(default=False),
        ),
    ]
