# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_inventory_reserved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="stripe_payment_intent",
            new_name="payment_reference",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="stripe_charge_id",
            new_name="transaction_reference",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="refund_id",
            new_name="refund_reference",
        ),
        migrations.AddField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[("DEMO", "Demo Checkout")],
                default="DEMO",
                max_length=20,
            ),
        ),
    ]
