# Generated by Django 5.0.6 on 2026-04-27 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('game', models.CharField(choices=[('POKEMON', 'Pokémon'), ('ONE_PIECE', 'One Piece'), ('YUGIOH', 'Yu-Gi-Oh!'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'products_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('set_name', models.CharField(blank=True, max_length=150)),
                ('set_code', models.CharField(blank=True, max_length=20)),
                ('card_number', models.CharField(blank=True, max_length=20)),
                ('rarity', models.CharField(blank=True, choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare'), ('RARE_HOLO', 'Rare Holo'), ('ULTRA_RARE', 'Ultra Rare'), ('SECRET_RARE', 'Secret Rare'), ('FULL_ART', 'Full Art'), ('PROMO', 'Promo')], max_length=50)),
                ('condition', models.CharField(choices=[('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Damaged')], default='NM', max_length=10)),
                ('language', models.CharField(default='English', max_length=30)),
                ('is_foil', models.BooleanField(default=False)),
                ('is_first_edition', models.BooleanField(default=False)),
                ('product_type', models.CharField(choices=[('SINGLE', 'Single Card'), ('PACK', 'Booster Pack'), ('BOX', 'Booster Box'), ('BUNDLE', 'Bundle'), ('TIN', 'Tin')], default='SINGLE', max_length=30)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('image_back', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'db_table': 'products_product',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'), models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'), models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'), models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx')],
            },
        ),
    ]
