# Generated by Django 6.0.4 on 2026-04-28 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="image_url",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="image_back",
            new_name="image_back_url",
        ),
    ]
